[DSCP-387] fix config full sample
DisciplinaOU/disciplina pull request #366
Opened 2019-01-17 19:55 UTC by pasqu4le

### Description

This PR fixes a couple of mistakes in the full configuration example.

### YT issue

https://issues.serokell.io/issue/DSCP-387

### Checklist

Hint: a perfect PR has all the checkmarks set.

Possible related changes (conditional):
- [ ] I added tests if required, in case they are:
  - Covering new introduced functionality (feature).
  - Regression tests preventing the bug from silently reappearing again (bugfix).
- [ ] I have checked the [sample config](../tree/master/docs/config-full-sample.yaml) and [launch scripts](../tree/master/scripts/launch) and updated them if it was necessary (especially if executables or CLIs were changed).
- [ ] I have checked READMEs and changed them accordingly if it's necessary (the main [README.md](../tree/master/README.md) as well as subproject READMEs for all related executables).
- [ ] If a public API structure or/and data serialization was changed, I made sure that these changes are reflected in the:
  - [Swagger](../tree/master/specs/disciplina) API specs.
  - Any [related documentation](../tree/master/docs/api-types.md).
- [ ] If any public documentation was written, I have spellchecked it.

Stylistic (obligatory):
- [ ] My commit history is clean, descriptive and do not contain merge or revert commits or commits like "WIP".
- [ ] My code complies with the [style guide](../tree/master/docs/code-style.md).
- [ ] My code is documented (haddock) and these docs are decent (full enough and spellchecked).

2019-01-17 20:15 UTC, kirelagin requested changes

2019-01-17 20:15 UTC, kirelagin commented on docs/config-full-sample.yaml
> +        min-level: Debug
Gotta be `min-severity`.

2019-01-17 20:39 UTC, kirelagin approved these changes
Did not test, but checked against the source code and looks good.

2019-01-21 09:33 UTC, pasqu4le commented
@flyingleafe this PR is a fix for the configuration example. I just rebased and signed it and it should probably get merged.

2019-01-31 12:02 UTC, flyingleafe approved these changes

2019-01-31 20:27 UTC, merged